### ISSUE TITLE
Understanding of paper

### ISSUE THREAD

**Issue by Mrugankakarte** [atavakol/action-branching-agents#2]
Hi,

I was trying to understand your paper by relating to my problem where I have to select action from 
```
Dict(
attack:Discrete(2), 
back:Discrete(2), 
camera:Box(2,), 
forward:Discrete(2),
jump:Discrete(2), 
left:Discrete(2), 
place:Enum(none,dirt), 
right:Discrete(2), 
sneak:Discrete(2), 
sprint:Discrete(2)
)
```
Since simultaneous actions are possible(attack+jump, forward+jump), how do I select them using BDQN? As per my understanding, in BDQN we will be selecting max q-value from each action_stream. For example in `Bipedal-walker2D-v1` environment, action_space is like `[-1, 1, -1, 1]` that is there are 4 action streams and we will be predicting values for each action_stream? I am correct?
Also I am unable to comprehend the use of ` num_actions_pad = 33 # numb discrete sub-actions per action dimension` 

I will appreciate if you could kindly explain me this. Thanks!

**Comment by atavakol** [comment]
Hi Mrugank, 

While Branching Q-Learning applies to discrete action domains, the current implementation of our approach only applies to continuous-action domains via discretization. Therefore, we use the hyper-parameter `num_actions_pad = 33` to specify the granularity of discretization. That is, for a domain with original action-space of `Box(n,)` (meaning it has `n` action dimensions and each action dimension is continuous with a finite range), our discretization converts it to `[Discrete(33), Discrete(33), ..., Discrete(33)]`, which is a list with `n` elements. Our approach assumes a separate Q-approximator for each element in this list (i.e., you have `n` Q-functions, each with `33` output nodes), and shares some parameters among these Q-functions in the shared module. 

Our paper provides more information about all this: [https://arxiv.org/abs/1711.08946](https://arxiv.org/abs/1711.08946)

Hope this helps.
Arash

**Comment by Mrugankakarte** [comment]
I get it now!! Thanks a lot!
