### ISSUE TITLE
Multiplication with num_action_streams

### ISSUE THREAD

**Issue by rasorensen90** [atavakol/action-branching-agents#3]
I have a question regarding this line:
https://github.com/atavakol/action-branching-agents/blob/db6875df4c9fb8f4b904ec9da0178c9d1f808f47/agents/bdq/deepq/build_graph.py#L257

It is probably me who have missed something, but can you help me explain why you multiply with num_action_streams here?

**Comment by fabiopardo** [comment]
Hey. The multiplication symbol is a python way to create a list with the target Q-value repeated num_action_streams times. It simply says that the target for all of the branches is the same.

**Comment by rasorensen90** [comment]
Ah, I see. Thanks.
