### ISSUE TITLE
Cannot save the model from bdq.deepq.models.mlp_branching. Is there a way ?

### ISSUE THREAD

**Issue by DataGasmic** [atavakol/action-branching-agents#4]
Even after digging in the code, I couldn't find the way to save the model to be able to reuse it

**Comment by atavakol** [comment]
By default, the model is saved at the end of the training. See here:
https://github.com/atavakol/action-branching-agents/blob/db6875df4c9fb8f4b904ec9da0178c9d1f808f47/agents/bdq/train_continuous.py#L97-L103

If you wish to store the model frequently during the training, inside `learn_continuous_tasks` method (where the training routine takes place), you should use `ActWrapper` to wrap the `act` function (i.e., `ActWrapper(act, act_params)`) and use its `save()` and `load()` methods to save or load your model, respectively.
