### ISSUE TITLE
Requirements list required

### ISSUE THREAD

**Issue by ghost** [atavakol/action-branching-agents#6]
Hi, may I ask you to provide the requirements list for this project? It seems that for example Tensorflow 2.0 doesn't utilize .contrib.layers anymore. As I am a bit of a newbie in RL, I don't want to mess with the code too much until it doesn't work and I'm not sure which versions to use, that's why the question.

**Comment by atavakol** [comment]
Hi @Bartiik! This code is based on the very first release of the OpenAI's Baselines and thus all requirements can be found there. Visit this [link](https://github.com/openai/baselines/tree/958810ed1e78624c300e327a0c79212f2453cfb7) for the aforesaid version of Baselines. I'll be releasing a simplified version of this code based on Google's Dopamine framework sometime in the next month or so. If you're interested, please watch this space: [link to a future release](https://github.com/atavakol/action-hypergraph-networks). Also, there may be another implementation of this agent by my colleague soon [here](https://github.com/fabiopardo/tonic).

**Comment by ghost** [comment]
Thank you for your answer :) I am looking forward to see the mentioned implementation, and even more to check out the simplification. I am writing a master thesis about machine learning in manipulator control systems and I randomly found your article in google. Since then I was sure I'll need to try to implement it, so I can't wait for any updates :)

**Comment by atavakol** [comment]
Hi @Bartiik! The new implementation which I promised is now live: [github.com/atavakol/action-hypergraph-networks](https://github.com/atavakol/action-hypergraph-networks). Check the following agents from the mentioned repository: Branching-DQN and, the alternative approach, Hypergraph-DQN (HGQN) with rank-1 and a monotonic mixer. 

Let me know if you have any questions.
